timeout: 180s
steps:
- id: 'build:composer'
  name: 'eu.gcr.io/ingenerator-ci/ingenerator-php:8.1'
  entrypoint: 'composer'
  args:
  - 'install'
  - '--no-interaction'
- id: 'test:unit'
  name: 'eu.gcr.io/ingenerator-ci/ingenerator-php:8.1'
  dir: '/workspace'
  entrypoint: './vendor/bin/phpunit'
